---
version: '3.7'
services:
  es01:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.0'
    container_name: es01
    environment:
      node.name: es01
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./volume/es01
        target: /usr/share/elasticsearch/data
    ports:
      - '9200:9200'
  rabbit:
    image: 'rabbitmq:3.8.3'
    container_name: rabbit
    volumes:
      - type: bind
        source: ./volume/rabbit
        target: /var/lib/rabbitmq
    ports:
      - '5672:5672'
  pet-search:
    build: .
    container_name: pet-search
    ports:
      - "80:8080"
  pet-consumer:
    build: consumer.Dockerfile
    container_name: pet-consumer
